import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { FC } from 'react';
import Post from '../components/post';
import { prisma } from '../lib/prisma';
import styles from '../styles/Home.module.css';

interface IProfile {
  profile: {
    id: number;
    name: string;
    email: string;
    image: string;
    bio: string;
    userName: string;
  }[];
}

export interface IPost {
  posts: {
    id: number;
    title: string;
    content: string;
    image: string;
    User: {
      email: string;
      id: number;
      userName: string;
    };
  }[];
}
// import session form next auth
interface IHome extends IProfile, IPost {}

const Home: FC<IHome> = (props) => {
  const { profile, posts } = props;
  const { data: session, status } = useSession();

  const router = useRouter();

  const refreshData = () => {
    router.replace(router.asPath);
  };

  const handleSubmit = async (e: any) => {
    // Fix the type check of e
    e.preventDefault();
    const bio = e.currentTarget.bio.value;

    const email = e.target.user.value;

    await fetch('/api/profile', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ bio, email }),
    });
    refreshData();
  };
  const bioFrom = (
    <>
      <form onSubmit={handleSubmit}>
        <input type="bio" name="bio" placeholder="Please enter your bio" />
        <input
          type="email"
          name="user"
          // Remove this exclamtion mark in the future
          value={session?.user?.email!}
          disabled
        />
        <button type="submit">Submit</button>
      </form>
      <Link href="/api/auth/signout">
        <h1>Sign out</h1>
      </Link>
    </>
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {profile.map((bio) => {
          return (
            <div key={bio.id}>
              <h1>{bio.bio}</h1>
              <h1>{bio.email}</h1>
              <h1>{bio.userName}</h1>
            </div>
          );
        })}
        {status === 'authenticated' ? (
          bioFrom
        ) : (
          <div>
            <Link href="/api/auth/signin">
              <h1>Please sign in</h1>
            </Link>
          </div>
        )}
        <h1>Post</h1>
        <Post posts={posts} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  const profile = await prisma.profile.findMany();
  const posts = await prisma.post.findMany({
    select: {
      id: true,
      title: true,
      content: true,
      image: true,
      User: {
        select: {
          email: true,
          id: true,
        },
      },
    },
  });

  return {
    props: { profile, posts },
  };
}
